//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVenta.WsBanco {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.com.banco/", ConfigurationName="WsBanco.NroCuentaService")]
    public interface NroCuentaService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cNroTarjeta del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MVCVenta.WsBanco.obtenerTransaccionResponse obtenerTransaccion(MVCVenta.WsBanco.obtenerTransaccion request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerTransaccion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerTransaccion", Namespace="http://service.com.banco/", Order=0)]
        public MVCVenta.WsBanco.obtenerTransaccionBody Body;
        
        public obtenerTransaccion() {
        }
        
        public obtenerTransaccion(MVCVenta.WsBanco.obtenerTransaccionBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class obtenerTransaccionBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cNroTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cCodTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cTipoCuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double dMonto;
        
        public obtenerTransaccionBody() {
        }
        
        public obtenerTransaccionBody(string cNroTarjeta, string cCodTarjeta, string cTipoCuenta, double dMonto) {
            this.cNroTarjeta = cNroTarjeta;
            this.cCodTarjeta = cCodTarjeta;
            this.cTipoCuenta = cTipoCuenta;
            this.dMonto = dMonto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerTransaccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerTransaccionResponse", Namespace="http://service.com.banco/", Order=0)]
        public MVCVenta.WsBanco.obtenerTransaccionResponseBody Body;
        
        public obtenerTransaccionResponse() {
        }
        
        public obtenerTransaccionResponse(MVCVenta.WsBanco.obtenerTransaccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class obtenerTransaccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transaccion;
        
        public obtenerTransaccionResponseBody() {
        }
        
        public obtenerTransaccionResponseBody(string transaccion) {
            this.transaccion = transaccion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NroCuentaServiceChannel : MVCVenta.WsBanco.NroCuentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NroCuentaServiceClient : System.ServiceModel.ClientBase<MVCVenta.WsBanco.NroCuentaService>, MVCVenta.WsBanco.NroCuentaService {
        
        public NroCuentaServiceClient() {
        }
        
        public NroCuentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NroCuentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NroCuentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NroCuentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCVenta.WsBanco.obtenerTransaccionResponse MVCVenta.WsBanco.NroCuentaService.obtenerTransaccion(MVCVenta.WsBanco.obtenerTransaccion request) {
            return base.Channel.obtenerTransaccion(request);
        }
        
        public string obtenerTransaccion(string cNroTarjeta, string cCodTarjeta, string cTipoCuenta, double dMonto) {
            MVCVenta.WsBanco.obtenerTransaccion inValue = new MVCVenta.WsBanco.obtenerTransaccion();
            inValue.Body = new MVCVenta.WsBanco.obtenerTransaccionBody();
            inValue.Body.cNroTarjeta = cNroTarjeta;
            inValue.Body.cCodTarjeta = cCodTarjeta;
            inValue.Body.cTipoCuenta = cTipoCuenta;
            inValue.Body.dMonto = dMonto;
            MVCVenta.WsBanco.obtenerTransaccionResponse retVal = ((MVCVenta.WsBanco.NroCuentaService)(this)).obtenerTransaccion(inValue);
            return retVal.Body.transaccion;
        }
    }
}
