#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVenta.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Ventas")]
	public partial class VentaDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTB_Almacen(TB_Almacen instance);
    partial void UpdateTB_Almacen(TB_Almacen instance);
    partial void DeleteTB_Almacen(TB_Almacen instance);
    partial void InsertTB_Usuario(TB_Usuario instance);
    partial void UpdateTB_Usuario(TB_Usuario instance);
    partial void DeleteTB_Usuario(TB_Usuario instance);
    partial void InsertTB_Cliente(TB_Cliente instance);
    partial void UpdateTB_Cliente(TB_Cliente instance);
    partial void DeleteTB_Cliente(TB_Cliente instance);
    partial void InsertTB_Dominio(TB_Dominio instance);
    partial void UpdateTB_Dominio(TB_Dominio instance);
    partial void DeleteTB_Dominio(TB_Dominio instance);
    partial void InsertTB_PersonaJuridica(TB_PersonaJuridica instance);
    partial void UpdateTB_PersonaJuridica(TB_PersonaJuridica instance);
    partial void DeleteTB_PersonaJuridica(TB_PersonaJuridica instance);
    partial void InsertTB_PersonaNatural(TB_PersonaNatural instance);
    partial void UpdateTB_PersonaNatural(TB_PersonaNatural instance);
    partial void DeleteTB_PersonaNatural(TB_PersonaNatural instance);
    partial void InsertTB_Producto(TB_Producto instance);
    partial void UpdateTB_Producto(TB_Producto instance);
    partial void DeleteTB_Producto(TB_Producto instance);
    partial void InsertTB_Stock(TB_Stock instance);
    partial void UpdateTB_Stock(TB_Stock instance);
    partial void DeleteTB_Stock(TB_Stock instance);
    partial void InsertTB_Pedido(TB_Pedido instance);
    partial void UpdateTB_Pedido(TB_Pedido instance);
    partial void DeleteTB_Pedido(TB_Pedido instance);
    partial void InsertTB_DetallePedido(TB_DetallePedido instance);
    partial void UpdateTB_DetallePedido(TB_DetallePedido instance);
    partial void DeleteTB_DetallePedido(TB_DetallePedido instance);
    partial void InsertUbigeo(Ubigeo instance);
    partial void UpdateUbigeo(Ubigeo instance);
    partial void DeleteUbigeo(Ubigeo instance);
    #endregion
		
		public VentaDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_VentasConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VentaDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentaDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentaDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentaDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_Almacen> TB_Almacens
		{
			get
			{
				return this.GetTable<TB_Almacen>();
			}
		}
		
		public System.Data.Linq.Table<TB_Usuario> TB_Usuarios
		{
			get
			{
				return this.GetTable<TB_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<TB_Cliente> TB_Clientes
		{
			get
			{
				return this.GetTable<TB_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<TB_Dominio> TB_Dominios
		{
			get
			{
				return this.GetTable<TB_Dominio>();
			}
		}
		
		public System.Data.Linq.Table<TB_PersonaJuridica> TB_PersonaJuridicas
		{
			get
			{
				return this.GetTable<TB_PersonaJuridica>();
			}
		}
		
		public System.Data.Linq.Table<TB_PersonaNatural> TB_PersonaNaturals
		{
			get
			{
				return this.GetTable<TB_PersonaNatural>();
			}
		}
		
		public System.Data.Linq.Table<TB_Producto> TB_Productos
		{
			get
			{
				return this.GetTable<TB_Producto>();
			}
		}
		
		public System.Data.Linq.Table<TB_Stock> TB_Stocks
		{
			get
			{
				return this.GetTable<TB_Stock>();
			}
		}
		
		public System.Data.Linq.Table<TB_Pedido> TB_Pedido
		{
			get
			{
				return this.GetTable<TB_Pedido>();
			}
		}
		
		public System.Data.Linq.Table<TB_DetallePedido> TB_DetallePedido
		{
			get
			{
				return this.GetTable<TB_DetallePedido>();
			}
		}
		
		public System.Data.Linq.Table<Ubigeo> Ubigeo
		{
			get
			{
				return this.GetTable<Ubigeo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Almacen")]
	public partial class TB_Almacen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_eAlmacen;
		
		private string _cSucursal;
		
		private string _cDireccion;
		
		private EntitySet<TB_Stock> _TB_Stocks;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_eAlmacenChanging(int value);
    partial void OnPk_eAlmacenChanged();
    partial void OncSucursalChanging(string value);
    partial void OncSucursalChanged();
    partial void OncDireccionChanging(string value);
    partial void OncDireccionChanged();
    #endregion
		
		public TB_Almacen()
		{
			this._TB_Stocks = new EntitySet<TB_Stock>(new Action<TB_Stock>(this.attach_TB_Stocks), new Action<TB_Stock>(this.detach_TB_Stocks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_eAlmacen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_eAlmacen
		{
			get
			{
				return this._Pk_eAlmacen;
			}
			set
			{
				if ((this._Pk_eAlmacen != value))
				{
					this.OnPk_eAlmacenChanging(value);
					this.SendPropertyChanging();
					this._Pk_eAlmacen = value;
					this.SendPropertyChanged("Pk_eAlmacen");
					this.OnPk_eAlmacenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSucursal", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string cSucursal
		{
			get
			{
				return this._cSucursal;
			}
			set
			{
				if ((this._cSucursal != value))
				{
					this.OncSucursalChanging(value);
					this.SendPropertyChanging();
					this._cSucursal = value;
					this.SendPropertyChanged("cSucursal");
					this.OncSucursalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDireccion", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string cDireccion
		{
			get
			{
				return this._cDireccion;
			}
			set
			{
				if ((this._cDireccion != value))
				{
					this.OncDireccionChanging(value);
					this.SendPropertyChanging();
					this._cDireccion = value;
					this.SendPropertyChanged("cDireccion");
					this.OncDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Almacen_TB_Stock", Storage="_TB_Stocks", ThisKey="Pk_eAlmacen", OtherKey="Fk_eAlmacen")]
		public EntitySet<TB_Stock> TB_Stocks
		{
			get
			{
				return this._TB_Stocks;
			}
			set
			{
				this._TB_Stocks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Stocks(TB_Stock entity)
		{
			this.SendPropertyChanging();
			entity.TB_Almacen = this;
		}
		
		private void detach_TB_Stocks(TB_Stock entity)
		{
			this.SendPropertyChanging();
			entity.TB_Almacen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Usuario")]
	public partial class TB_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_eUsuario;
		
		private System.Nullable<int> _Fk_eCliente;
		
		private string _cUsuario;
		
		private string _cContrasena;
		
		private System.DateTime _dFecRegistro;
		
		private EntityRef<TB_Cliente> _TB_Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_eUsuarioChanging(int value);
    partial void OnPk_eUsuarioChanged();
    partial void OnFk_eClienteChanging(System.Nullable<int> value);
    partial void OnFk_eClienteChanged();
    partial void OncUsuarioChanging(string value);
    partial void OncUsuarioChanged();
    partial void OncContrasenaChanging(string value);
    partial void OncContrasenaChanged();
    partial void OndFecRegistroChanging(System.DateTime value);
    partial void OndFecRegistroChanged();
    #endregion
		
		public TB_Usuario()
		{
			this._TB_Cliente = default(EntityRef<TB_Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_eUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_eUsuario
		{
			get
			{
				return this._Pk_eUsuario;
			}
			set
			{
				if ((this._Pk_eUsuario != value))
				{
					this.OnPk_eUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Pk_eUsuario = value;
					this.SendPropertyChanged("Pk_eUsuario");
					this.OnPk_eUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_eCliente", DbType="Int")]
		public System.Nullable<int> Fk_eCliente
		{
			get
			{
				return this._Fk_eCliente;
			}
			set
			{
				if ((this._Fk_eCliente != value))
				{
					if (this._TB_Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_eClienteChanging(value);
					this.SendPropertyChanging();
					this._Fk_eCliente = value;
					this.SendPropertyChanged("Fk_eCliente");
					this.OnFk_eClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cUsuario
		{
			get
			{
				return this._cUsuario;
			}
			set
			{
				if ((this._cUsuario != value))
				{
					this.OncUsuarioChanging(value);
					this.SendPropertyChanging();
					this._cUsuario = value;
					this.SendPropertyChanged("cUsuario");
					this.OncUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cContrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cContrasena
		{
			get
			{
				return this._cContrasena;
			}
			set
			{
				if ((this._cContrasena != value))
				{
					this.OncContrasenaChanging(value);
					this.SendPropertyChanging();
					this._cContrasena = value;
					this.SendPropertyChanged("cContrasena");
					this.OncContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dFecRegistro", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime dFecRegistro
		{
			get
			{
				return this._dFecRegistro;
			}
			set
			{
				if ((this._dFecRegistro != value))
				{
					this.OndFecRegistroChanging(value);
					this.SendPropertyChanging();
					this._dFecRegistro = value;
					this.SendPropertyChanged("dFecRegistro");
					this.OndFecRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Cliente_TB_Usuario", Storage="_TB_Cliente", ThisKey="Fk_eCliente", OtherKey="Pk_eCliente", IsForeignKey=true)]
		public TB_Cliente TB_Cliente
		{
			get
			{
				return this._TB_Cliente.Entity;
			}
			set
			{
				TB_Cliente previousValue = this._TB_Cliente.Entity;
				if (((previousValue != value) 
							|| (this._TB_Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Cliente.Entity = null;
						previousValue.TB_Usuarios.Remove(this);
					}
					this._TB_Cliente.Entity = value;
					if ((value != null))
					{
						value.TB_Usuarios.Add(this);
						this._Fk_eCliente = value.Pk_eCliente;
					}
					else
					{
						this._Fk_eCliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Cliente")]
	public partial class TB_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_eCliente;
		
		private string _cTelefono;
		
		private string _cDireccion;
		
		private string _cTipCliente;
		
		private System.DateTime _dFecRegistro;
		
		private string _codDepartamento;
		
		private string _codProvincia;
		
		private string _codDistrito;
		
		private EntitySet<TB_Usuario> _TB_Usuarios;
		
		private EntitySet<TB_PersonaJuridica> _TB_PersonaJuridicas;
		
		private EntitySet<TB_PersonaNatural> _TB_PersonaNaturals;
		
		private EntitySet<TB_Pedido> _TB_Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_eClienteChanging(int value);
    partial void OnPk_eClienteChanged();
    partial void OncTelefonoChanging(string value);
    partial void OncTelefonoChanged();
    partial void OncDireccionChanging(string value);
    partial void OncDireccionChanged();
    partial void OncTipClienteChanging(string value);
    partial void OncTipClienteChanged();
    partial void OndFecRegistroChanging(System.DateTime value);
    partial void OndFecRegistroChanged();
    partial void OncodDepartamentoChanging(string value);
    partial void OncodDepartamentoChanged();
    partial void OncodProvinciaChanging(string value);
    partial void OncodProvinciaChanged();
    partial void OncodDistritoChanging(string value);
    partial void OncodDistritoChanged();
    #endregion
		
		public TB_Cliente()
		{
			this._TB_Usuarios = new EntitySet<TB_Usuario>(new Action<TB_Usuario>(this.attach_TB_Usuarios), new Action<TB_Usuario>(this.detach_TB_Usuarios));
			this._TB_PersonaJuridicas = new EntitySet<TB_PersonaJuridica>(new Action<TB_PersonaJuridica>(this.attach_TB_PersonaJuridicas), new Action<TB_PersonaJuridica>(this.detach_TB_PersonaJuridicas));
			this._TB_PersonaNaturals = new EntitySet<TB_PersonaNatural>(new Action<TB_PersonaNatural>(this.attach_TB_PersonaNaturals), new Action<TB_PersonaNatural>(this.detach_TB_PersonaNaturals));
			this._TB_Pedido = new EntitySet<TB_Pedido>(new Action<TB_Pedido>(this.attach_TB_Pedido), new Action<TB_Pedido>(this.detach_TB_Pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_eCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_eCliente
		{
			get
			{
				return this._Pk_eCliente;
			}
			set
			{
				if ((this._Pk_eCliente != value))
				{
					this.OnPk_eClienteChanging(value);
					this.SendPropertyChanging();
					this._Pk_eCliente = value;
					this.SendPropertyChanged("Pk_eCliente");
					this.OnPk_eClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cTelefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cTelefono
		{
			get
			{
				return this._cTelefono;
			}
			set
			{
				if ((this._cTelefono != value))
				{
					this.OncTelefonoChanging(value);
					this.SendPropertyChanging();
					this._cTelefono = value;
					this.SendPropertyChanged("cTelefono");
					this.OncTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDireccion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cDireccion
		{
			get
			{
				return this._cDireccion;
			}
			set
			{
				if ((this._cDireccion != value))
				{
					this.OncDireccionChanging(value);
					this.SendPropertyChanging();
					this._cDireccion = value;
					this.SendPropertyChanged("cDireccion");
					this.OncDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cTipCliente", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string cTipCliente
		{
			get
			{
				return this._cTipCliente;
			}
			set
			{
				if ((this._cTipCliente != value))
				{
					this.OncTipClienteChanging(value);
					this.SendPropertyChanging();
					this._cTipCliente = value;
					this.SendPropertyChanged("cTipCliente");
					this.OncTipClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dFecRegistro", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime dFecRegistro
		{
			get
			{
				return this._dFecRegistro;
			}
			set
			{
				if ((this._dFecRegistro != value))
				{
					this.OndFecRegistroChanging(value);
					this.SendPropertyChanging();
					this._dFecRegistro = value;
					this.SendPropertyChanged("dFecRegistro");
					this.OndFecRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDepartamento", DbType="VarChar(2) NULL", CanBeNull=false)]
		public string codDepartamento
		{
			get
			{
				return this._codDepartamento;
			}
			set
			{
				if ((this._codDepartamento != value))
				{
					this.OncodDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._codDepartamento = value;
					this.SendPropertyChanged("codDepartamento");
					this.OncodDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProvincia", DbType="VarChar(2) NULL", CanBeNull=false)]
		public string codProvincia
		{
			get
			{
				return this._codProvincia;
			}
			set
			{
				if ((this._codProvincia != value))
				{
					this.OncodProvinciaChanging(value);
					this.SendPropertyChanging();
					this._codProvincia = value;
					this.SendPropertyChanged("codProvincia");
					this.OncodProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDistrito", DbType="VarChar(2) NULL", CanBeNull=false)]
		public string codDistrito
		{
			get
			{
				return this._codDistrito;
			}
			set
			{
				if ((this._codDistrito != value))
				{
					this.OncodDistritoChanging(value);
					this.SendPropertyChanging();
					this._codDistrito = value;
					this.SendPropertyChanged("codDistrito");
					this.OncodDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Cliente_TB_Usuario", Storage="_TB_Usuarios", ThisKey="Pk_eCliente", OtherKey="Fk_eCliente")]
		public EntitySet<TB_Usuario> TB_Usuarios
		{
			get
			{
				return this._TB_Usuarios;
			}
			set
			{
				this._TB_Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Cliente_TB_PersonaJuridica", Storage="_TB_PersonaJuridicas", ThisKey="Pk_eCliente", OtherKey="Fk_eCliente")]
		public EntitySet<TB_PersonaJuridica> TB_PersonaJuridicas
		{
			get
			{
				return this._TB_PersonaJuridicas;
			}
			set
			{
				this._TB_PersonaJuridicas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Cliente_TB_PersonaNatural", Storage="_TB_PersonaNaturals", ThisKey="Pk_eCliente", OtherKey="Fk_eCliente")]
		public EntitySet<TB_PersonaNatural> TB_PersonaNaturals
		{
			get
			{
				return this._TB_PersonaNaturals;
			}
			set
			{
				this._TB_PersonaNaturals.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Cliente_TB_Pedido", Storage="_TB_Pedido", ThisKey="Pk_eCliente", OtherKey="Fk_eCliente")]
		public EntitySet<TB_Pedido> TB_Pedido
		{
			get
			{
				return this._TB_Pedido;
			}
			set
			{
				this._TB_Pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Usuarios(TB_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.TB_Cliente = this;
		}
		
		private void detach_TB_Usuarios(TB_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.TB_Cliente = null;
		}
		
		private void attach_TB_PersonaJuridicas(TB_PersonaJuridica entity)
		{
			this.SendPropertyChanging();
			entity.TB_Cliente = this;
		}
		
		private void detach_TB_PersonaJuridicas(TB_PersonaJuridica entity)
		{
			this.SendPropertyChanging();
			entity.TB_Cliente = null;
		}
		
		private void attach_TB_PersonaNaturals(TB_PersonaNatural entity)
		{
			this.SendPropertyChanging();
			entity.TB_Cliente = this;
		}
		
		private void detach_TB_PersonaNaturals(TB_PersonaNatural entity)
		{
			this.SendPropertyChanging();
			entity.TB_Cliente = null;
		}
		
		private void attach_TB_Pedido(TB_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.TB_Cliente = this;
		}
		
		private void detach_TB_Pedido(TB_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.TB_Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Dominio")]
	public partial class TB_Dominio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_eDominio;
		
		private string _cTipo;
		
		private string _cDescripcion;
		
		private EntitySet<TB_Producto> _TB_Productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_eDominioChanging(int value);
    partial void OnPk_eDominioChanged();
    partial void OncTipoChanging(string value);
    partial void OncTipoChanged();
    partial void OncDescripcionChanging(string value);
    partial void OncDescripcionChanged();
    #endregion
		
		public TB_Dominio()
		{
			this._TB_Productos = new EntitySet<TB_Producto>(new Action<TB_Producto>(this.attach_TB_Productos), new Action<TB_Producto>(this.detach_TB_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_eDominio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_eDominio
		{
			get
			{
				return this._Pk_eDominio;
			}
			set
			{
				if ((this._Pk_eDominio != value))
				{
					this.OnPk_eDominioChanging(value);
					this.SendPropertyChanging();
					this._Pk_eDominio = value;
					this.SendPropertyChanged("Pk_eDominio");
					this.OnPk_eDominioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cTipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cTipo
		{
			get
			{
				return this._cTipo;
			}
			set
			{
				if ((this._cTipo != value))
				{
					this.OncTipoChanging(value);
					this.SendPropertyChanging();
					this._cTipo = value;
					this.SendPropertyChanged("cTipo");
					this.OncTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDescripcion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cDescripcion
		{
			get
			{
				return this._cDescripcion;
			}
			set
			{
				if ((this._cDescripcion != value))
				{
					this.OncDescripcionChanging(value);
					this.SendPropertyChanging();
					this._cDescripcion = value;
					this.SendPropertyChanged("cDescripcion");
					this.OncDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Dominio_TB_Producto", Storage="_TB_Productos", ThisKey="Pk_eDominio", OtherKey="Fk_eDominio")]
		public EntitySet<TB_Producto> TB_Productos
		{
			get
			{
				return this._TB_Productos;
			}
			set
			{
				this._TB_Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Productos(TB_Producto entity)
		{
			this.SendPropertyChanging();
			entity.TB_Dominio = this;
		}
		
		private void detach_TB_Productos(TB_Producto entity)
		{
			this.SendPropertyChanging();
			entity.TB_Dominio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PersonaJuridica")]
	public partial class TB_PersonaJuridica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_ePerJuridica;
		
		private System.Nullable<int> _Fk_eCliente;
		
		private string _cRuc;
		
		private string _cRazSocial;
		
		private EntityRef<TB_Cliente> _TB_Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_ePerJuridicaChanging(int value);
    partial void OnPk_ePerJuridicaChanged();
    partial void OnFk_eClienteChanging(System.Nullable<int> value);
    partial void OnFk_eClienteChanged();
    partial void OncRucChanging(string value);
    partial void OncRucChanged();
    partial void OncRazSocialChanging(string value);
    partial void OncRazSocialChanged();
    #endregion
		
		public TB_PersonaJuridica()
		{
			this._TB_Cliente = default(EntityRef<TB_Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_ePerJuridica", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_ePerJuridica
		{
			get
			{
				return this._Pk_ePerJuridica;
			}
			set
			{
				if ((this._Pk_ePerJuridica != value))
				{
					this.OnPk_ePerJuridicaChanging(value);
					this.SendPropertyChanging();
					this._Pk_ePerJuridica = value;
					this.SendPropertyChanged("Pk_ePerJuridica");
					this.OnPk_ePerJuridicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_eCliente", DbType="Int")]
		public System.Nullable<int> Fk_eCliente
		{
			get
			{
				return this._Fk_eCliente;
			}
			set
			{
				if ((this._Fk_eCliente != value))
				{
					if (this._TB_Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_eClienteChanging(value);
					this.SendPropertyChanging();
					this._Fk_eCliente = value;
					this.SendPropertyChanged("Fk_eCliente");
					this.OnFk_eClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cRuc", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string cRuc
		{
			get
			{
				return this._cRuc;
			}
			set
			{
				if ((this._cRuc != value))
				{
					this.OncRucChanging(value);
					this.SendPropertyChanging();
					this._cRuc = value;
					this.SendPropertyChanged("cRuc");
					this.OncRucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cRazSocial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cRazSocial
		{
			get
			{
				return this._cRazSocial;
			}
			set
			{
				if ((this._cRazSocial != value))
				{
					this.OncRazSocialChanging(value);
					this.SendPropertyChanging();
					this._cRazSocial = value;
					this.SendPropertyChanged("cRazSocial");
					this.OncRazSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Cliente_TB_PersonaJuridica", Storage="_TB_Cliente", ThisKey="Fk_eCliente", OtherKey="Pk_eCliente", IsForeignKey=true)]
		public TB_Cliente TB_Cliente
		{
			get
			{
				return this._TB_Cliente.Entity;
			}
			set
			{
				TB_Cliente previousValue = this._TB_Cliente.Entity;
				if (((previousValue != value) 
							|| (this._TB_Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Cliente.Entity = null;
						previousValue.TB_PersonaJuridicas.Remove(this);
					}
					this._TB_Cliente.Entity = value;
					if ((value != null))
					{
						value.TB_PersonaJuridicas.Add(this);
						this._Fk_eCliente = value.Pk_eCliente;
					}
					else
					{
						this._Fk_eCliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PersonaNatural")]
	public partial class TB_PersonaNatural : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_ePerNatural;
		
		private System.Nullable<int> _Fk_eCliente;
		
		private string _cDNI;
		
		private string _cNombres;
		
		private string _cApellidos;
		
		private EntityRef<TB_Cliente> _TB_Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_ePerNaturalChanging(int value);
    partial void OnPk_ePerNaturalChanged();
    partial void OnFk_eClienteChanging(System.Nullable<int> value);
    partial void OnFk_eClienteChanged();
    partial void OncDNIChanging(string value);
    partial void OncDNIChanged();
    partial void OncNombresChanging(string value);
    partial void OncNombresChanged();
    partial void OncApellidosChanging(string value);
    partial void OncApellidosChanged();
    #endregion
		
		public TB_PersonaNatural()
		{
			this._TB_Cliente = default(EntityRef<TB_Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_ePerNatural", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_ePerNatural
		{
			get
			{
				return this._Pk_ePerNatural;
			}
			set
			{
				if ((this._Pk_ePerNatural != value))
				{
					this.OnPk_ePerNaturalChanging(value);
					this.SendPropertyChanging();
					this._Pk_ePerNatural = value;
					this.SendPropertyChanged("Pk_ePerNatural");
					this.OnPk_ePerNaturalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_eCliente", DbType="Int")]
		public System.Nullable<int> Fk_eCliente
		{
			get
			{
				return this._Fk_eCliente;
			}
			set
			{
				if ((this._Fk_eCliente != value))
				{
					if (this._TB_Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_eClienteChanging(value);
					this.SendPropertyChanging();
					this._Fk_eCliente = value;
					this.SendPropertyChanged("Fk_eCliente");
					this.OnFk_eClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDNI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cDNI
		{
			get
			{
				return this._cDNI;
			}
			set
			{
				if ((this._cDNI != value))
				{
					this.OncDNIChanging(value);
					this.SendPropertyChanging();
					this._cDNI = value;
					this.SendPropertyChanged("cDNI");
					this.OncDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cNombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cNombres
		{
			get
			{
				return this._cNombres;
			}
			set
			{
				if ((this._cNombres != value))
				{
					this.OncNombresChanging(value);
					this.SendPropertyChanging();
					this._cNombres = value;
					this.SendPropertyChanged("cNombres");
					this.OncNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cApellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cApellidos
		{
			get
			{
				return this._cApellidos;
			}
			set
			{
				if ((this._cApellidos != value))
				{
					this.OncApellidosChanging(value);
					this.SendPropertyChanging();
					this._cApellidos = value;
					this.SendPropertyChanged("cApellidos");
					this.OncApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Cliente_TB_PersonaNatural", Storage="_TB_Cliente", ThisKey="Fk_eCliente", OtherKey="Pk_eCliente", IsForeignKey=true)]
		public TB_Cliente TB_Cliente
		{
			get
			{
				return this._TB_Cliente.Entity;
			}
			set
			{
				TB_Cliente previousValue = this._TB_Cliente.Entity;
				if (((previousValue != value) 
							|| (this._TB_Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Cliente.Entity = null;
						previousValue.TB_PersonaNaturals.Remove(this);
					}
					this._TB_Cliente.Entity = value;
					if ((value != null))
					{
						value.TB_PersonaNaturals.Add(this);
						this._Fk_eCliente = value.Pk_eCliente;
					}
					else
					{
						this._Fk_eCliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Producto")]
	public partial class TB_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_eProducto;
		
		private int _Fk_eDominio;
		
		private string _cDescripcion;
		
		private decimal _dPrecio;
		
		private string _cEspecificacion;
		
		private string _bImagen;
		
		private decimal _dPeso;
		
		private EntitySet<TB_Stock> _TB_Stocks;
		
		private EntitySet<TB_DetallePedido> _TB_DetallePedido;
		
		private EntityRef<TB_Dominio> _TB_Dominio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_eProductoChanging(int value);
    partial void OnPk_eProductoChanged();
    partial void OnFk_eDominioChanging(int value);
    partial void OnFk_eDominioChanged();
    partial void OncDescripcionChanging(string value);
    partial void OncDescripcionChanged();
    partial void OndPrecioChanging(decimal value);
    partial void OndPrecioChanged();
    partial void OncEspecificacionChanging(string value);
    partial void OncEspecificacionChanged();
    partial void OnbImagenChanging(string value);
    partial void OnbImagenChanged();
    partial void OndPesoChanging(decimal value);
    partial void OndPesoChanged();
    #endregion
		
		public TB_Producto()
		{
			this._TB_Stocks = new EntitySet<TB_Stock>(new Action<TB_Stock>(this.attach_TB_Stocks), new Action<TB_Stock>(this.detach_TB_Stocks));
			this._TB_DetallePedido = new EntitySet<TB_DetallePedido>(new Action<TB_DetallePedido>(this.attach_TB_DetallePedido), new Action<TB_DetallePedido>(this.detach_TB_DetallePedido));
			this._TB_Dominio = default(EntityRef<TB_Dominio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_eProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_eProducto
		{
			get
			{
				return this._Pk_eProducto;
			}
			set
			{
				if ((this._Pk_eProducto != value))
				{
					this.OnPk_eProductoChanging(value);
					this.SendPropertyChanging();
					this._Pk_eProducto = value;
					this.SendPropertyChanged("Pk_eProducto");
					this.OnPk_eProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_eDominio", DbType="Int NOT NULL")]
		public int Fk_eDominio
		{
			get
			{
				return this._Fk_eDominio;
			}
			set
			{
				if ((this._Fk_eDominio != value))
				{
					if (this._TB_Dominio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_eDominioChanging(value);
					this.SendPropertyChanging();
					this._Fk_eDominio = value;
					this.SendPropertyChanged("Fk_eDominio");
					this.OnFk_eDominioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDescripcion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cDescripcion
		{
			get
			{
				return this._cDescripcion;
			}
			set
			{
				if ((this._cDescripcion != value))
				{
					this.OncDescripcionChanging(value);
					this.SendPropertyChanging();
					this._cDescripcion = value;
					this.SendPropertyChanged("cDescripcion");
					this.OncDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dPrecio", DbType="Decimal(18,0) NOT NULL")]
		public decimal dPrecio
		{
			get
			{
				return this._dPrecio;
			}
			set
			{
				if ((this._dPrecio != value))
				{
					this.OndPrecioChanging(value);
					this.SendPropertyChanging();
					this._dPrecio = value;
					this.SendPropertyChanged("dPrecio");
					this.OndPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cEspecificacion", DbType="VarChar(200)")]
		public string cEspecificacion
		{
			get
			{
				return this._cEspecificacion;
			}
			set
			{
				if ((this._cEspecificacion != value))
				{
					this.OncEspecificacionChanging(value);
					this.SendPropertyChanging();
					this._cEspecificacion = value;
					this.SendPropertyChanged("cEspecificacion");
					this.OncEspecificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bImagen", DbType="VarChar(100)")]
		public string bImagen
		{
			get
			{
				return this._bImagen;
			}
			set
			{
				if ((this._bImagen != value))
				{
					this.OnbImagenChanging(value);
					this.SendPropertyChanging();
					this._bImagen = value;
					this.SendPropertyChanged("bImagen");
					this.OnbImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dPeso", DbType="Decimal(18,2)  NULL")]
		public decimal dPeso
		{
			get
			{
				return this._dPeso;
			}
			set
			{
				if ((this._dPeso != value))
				{
					this.OndPesoChanging(value);
					this.SendPropertyChanging();
					this._dPeso = value;
					this.SendPropertyChanged("dPeso");
					this.OndPesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Producto_TB_Stock", Storage="_TB_Stocks", ThisKey="Pk_eProducto", OtherKey="Fk_eProducto")]
		public EntitySet<TB_Stock> TB_Stocks
		{
			get
			{
				return this._TB_Stocks;
			}
			set
			{
				this._TB_Stocks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Producto_TB_DetallePedido", Storage="_TB_DetallePedido", ThisKey="Pk_eProducto", OtherKey="Fk_eProducto")]
		public EntitySet<TB_DetallePedido> TB_DetallePedido
		{
			get
			{
				return this._TB_DetallePedido;
			}
			set
			{
				this._TB_DetallePedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Dominio_TB_Producto", Storage="_TB_Dominio", ThisKey="Fk_eDominio", OtherKey="Pk_eDominio", IsForeignKey=true)]
		public TB_Dominio TB_Dominio
		{
			get
			{
				return this._TB_Dominio.Entity;
			}
			set
			{
				TB_Dominio previousValue = this._TB_Dominio.Entity;
				if (((previousValue != value) 
							|| (this._TB_Dominio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Dominio.Entity = null;
						previousValue.TB_Productos.Remove(this);
					}
					this._TB_Dominio.Entity = value;
					if ((value != null))
					{
						value.TB_Productos.Add(this);
						this._Fk_eDominio = value.Pk_eDominio;
					}
					else
					{
						this._Fk_eDominio = default(int);
					}
					this.SendPropertyChanged("TB_Dominio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Stocks(TB_Stock entity)
		{
			this.SendPropertyChanging();
			entity.TB_Producto = this;
		}
		
		private void detach_TB_Stocks(TB_Stock entity)
		{
			this.SendPropertyChanging();
			entity.TB_Producto = null;
		}
		
		private void attach_TB_DetallePedido(TB_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.TB_Producto = this;
		}
		
		private void detach_TB_DetallePedido(TB_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.TB_Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Stock")]
	public partial class TB_Stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_eStock;
		
		private int _Fk_eProducto;
		
		private int _Fk_eAlmacen;
		
		private int _eStockActual;
		
		private System.Nullable<int> _eStockMinimo;
		
		private EntityRef<TB_Almacen> _TB_Almacen;
		
		private EntityRef<TB_Producto> _TB_Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_eStockChanging(int value);
    partial void OnPk_eStockChanged();
    partial void OnFk_eProductoChanging(int value);
    partial void OnFk_eProductoChanged();
    partial void OnFk_eAlmacenChanging(int value);
    partial void OnFk_eAlmacenChanged();
    partial void OneStockActualChanging(int value);
    partial void OneStockActualChanged();
    partial void OneStockMinimoChanging(System.Nullable<int> value);
    partial void OneStockMinimoChanged();
    #endregion
		
		public TB_Stock()
		{
			this._TB_Almacen = default(EntityRef<TB_Almacen>);
			this._TB_Producto = default(EntityRef<TB_Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_eStock", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_eStock
		{
			get
			{
				return this._Pk_eStock;
			}
			set
			{
				if ((this._Pk_eStock != value))
				{
					this.OnPk_eStockChanging(value);
					this.SendPropertyChanging();
					this._Pk_eStock = value;
					this.SendPropertyChanged("Pk_eStock");
					this.OnPk_eStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_eProducto", DbType="Int NOT NULL")]
		public int Fk_eProducto
		{
			get
			{
				return this._Fk_eProducto;
			}
			set
			{
				if ((this._Fk_eProducto != value))
				{
					if (this._TB_Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_eProductoChanging(value);
					this.SendPropertyChanging();
					this._Fk_eProducto = value;
					this.SendPropertyChanged("Fk_eProducto");
					this.OnFk_eProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_eAlmacen", DbType="Int NOT NULL")]
		public int Fk_eAlmacen
		{
			get
			{
				return this._Fk_eAlmacen;
			}
			set
			{
				if ((this._Fk_eAlmacen != value))
				{
					if (this._TB_Almacen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_eAlmacenChanging(value);
					this.SendPropertyChanging();
					this._Fk_eAlmacen = value;
					this.SendPropertyChanged("Fk_eAlmacen");
					this.OnFk_eAlmacenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eStockActual", DbType="Int NOT NULL")]
		public int eStockActual
		{
			get
			{
				return this._eStockActual;
			}
			set
			{
				if ((this._eStockActual != value))
				{
					this.OneStockActualChanging(value);
					this.SendPropertyChanging();
					this._eStockActual = value;
					this.SendPropertyChanged("eStockActual");
					this.OneStockActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eStockMinimo", DbType="Int")]
		public System.Nullable<int> eStockMinimo
		{
			get
			{
				return this._eStockMinimo;
			}
			set
			{
				if ((this._eStockMinimo != value))
				{
					this.OneStockMinimoChanging(value);
					this.SendPropertyChanging();
					this._eStockMinimo = value;
					this.SendPropertyChanged("eStockMinimo");
					this.OneStockMinimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Almacen_TB_Stock", Storage="_TB_Almacen", ThisKey="Fk_eAlmacen", OtherKey="Pk_eAlmacen", IsForeignKey=true)]
		public TB_Almacen TB_Almacen
		{
			get
			{
				return this._TB_Almacen.Entity;
			}
			set
			{
				TB_Almacen previousValue = this._TB_Almacen.Entity;
				if (((previousValue != value) 
							|| (this._TB_Almacen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Almacen.Entity = null;
						previousValue.TB_Stocks.Remove(this);
					}
					this._TB_Almacen.Entity = value;
					if ((value != null))
					{
						value.TB_Stocks.Add(this);
						this._Fk_eAlmacen = value.Pk_eAlmacen;
					}
					else
					{
						this._Fk_eAlmacen = default(int);
					}
					this.SendPropertyChanged("TB_Almacen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Producto_TB_Stock", Storage="_TB_Producto", ThisKey="Fk_eProducto", OtherKey="Pk_eProducto", IsForeignKey=true)]
		public TB_Producto TB_Producto
		{
			get
			{
				return this._TB_Producto.Entity;
			}
			set
			{
				TB_Producto previousValue = this._TB_Producto.Entity;
				if (((previousValue != value) 
							|| (this._TB_Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Producto.Entity = null;
						previousValue.TB_Stocks.Remove(this);
					}
					this._TB_Producto.Entity = value;
					if ((value != null))
					{
						value.TB_Stocks.Add(this);
						this._Fk_eProducto = value.Pk_eProducto;
					}
					else
					{
						this._Fk_eProducto = default(int);
					}
					this.SendPropertyChanged("TB_Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Pedido")]
	public partial class TB_Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_ePedido;
		
		private int _Fk_eCliente;
		
		private System.DateTime _fFechaRegistro;
		
		private string _cDestinatario;
		
		private decimal _mTotal;
		
		private string _cNumTarjeta;
		
		private int _eCodTarjeta;
		
		private string _cTipoPago;
		
		private string _cNroTransaccion;
		
		private string _cDireccionDestinatario;
		
		private string _codDepartamento;
		
		private string _codProvincia;
		
		private string _codDistrito;
		
		private EntitySet<TB_DetallePedido> _TB_DetallePedido;
		
		private EntityRef<TB_Cliente> _TB_Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_ePedidoChanging(int value);
    partial void OnPk_ePedidoChanged();
    partial void OnFk_eClienteChanging(int value);
    partial void OnFk_eClienteChanged();
    partial void OnfFechaRegistroChanging(System.DateTime value);
    partial void OnfFechaRegistroChanged();
    partial void OncDestinatarioChanging(string value);
    partial void OncDestinatarioChanged();
    partial void OnmTotalChanging(decimal value);
    partial void OnmTotalChanged();
    partial void OncNumTarjetaChanging(string value);
    partial void OncNumTarjetaChanged();
    partial void OneCodTarjetaChanging(int value);
    partial void OneCodTarjetaChanged();
    partial void OncTipoPagoChanging(string value);
    partial void OncTipoPagoChanged();
    partial void OncNroTransaccionChanging(string value);
    partial void OncNroTransaccionChanged();
    partial void OncDireccionDestinatarioChanging(string value);
    partial void OncDireccionDestinatarioChanged();
    partial void OncodDepartamentoChanging(string value);
    partial void OncodDepartamentoChanged();
    partial void OncodProvinciaChanging(string value);
    partial void OncodProvinciaChanged();
    partial void OncodDistritoChanging(string value);
    partial void OncodDistritoChanged();
    #endregion
		
		public TB_Pedido()
		{
			this._TB_DetallePedido = new EntitySet<TB_DetallePedido>(new Action<TB_DetallePedido>(this.attach_TB_DetallePedido), new Action<TB_DetallePedido>(this.detach_TB_DetallePedido));
			this._TB_Cliente = default(EntityRef<TB_Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_ePedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_ePedido
		{
			get
			{
				return this._Pk_ePedido;
			}
			set
			{
				if ((this._Pk_ePedido != value))
				{
					this.OnPk_ePedidoChanging(value);
					this.SendPropertyChanging();
					this._Pk_ePedido = value;
					this.SendPropertyChanged("Pk_ePedido");
					this.OnPk_ePedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_eCliente", DbType="Int NOT NULL")]
		public int Fk_eCliente
		{
			get
			{
				return this._Fk_eCliente;
			}
			set
			{
				if ((this._Fk_eCliente != value))
				{
					if (this._TB_Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_eClienteChanging(value);
					this.SendPropertyChanging();
					this._Fk_eCliente = value;
					this.SendPropertyChanged("Fk_eCliente");
					this.OnFk_eClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fFechaRegistro", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime fFechaRegistro
		{
			get
			{
				return this._fFechaRegistro;
			}
			set
			{
				if ((this._fFechaRegistro != value))
				{
					this.OnfFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fFechaRegistro = value;
					this.SendPropertyChanged("fFechaRegistro");
					this.OnfFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDestinatario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string cDestinatario
		{
			get
			{
				return this._cDestinatario;
			}
			set
			{
				if ((this._cDestinatario != value))
				{
					this.OncDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._cDestinatario = value;
					this.SendPropertyChanged("cDestinatario");
					this.OncDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mTotal", DbType="Money NOT NULL")]
		public decimal mTotal
		{
			get
			{
				return this._mTotal;
			}
			set
			{
				if ((this._mTotal != value))
				{
					this.OnmTotalChanging(value);
					this.SendPropertyChanging();
					this._mTotal = value;
					this.SendPropertyChanged("mTotal");
					this.OnmTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cNumTarjeta", DbType="VarChar(15)")]
		public string cNumTarjeta
		{
			get
			{
				return this._cNumTarjeta;
			}
			set
			{
				if ((this._cNumTarjeta != value))
				{
					this.OncNumTarjetaChanging(value);
					this.SendPropertyChanging();
					this._cNumTarjeta = value;
					this.SendPropertyChanged("cNumTarjeta");
					this.OncNumTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eCodTarjeta", DbType="Int NOT NULL")]
		public int eCodTarjeta
		{
			get
			{
				return this._eCodTarjeta;
			}
			set
			{
				if ((this._eCodTarjeta != value))
				{
					this.OneCodTarjetaChanging(value);
					this.SendPropertyChanging();
					this._eCodTarjeta = value;
					this.SendPropertyChanged("eCodTarjeta");
					this.OneCodTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cTipoPago", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cTipoPago
		{
			get
			{
				return this._cTipoPago;
			}
			set
			{
				if ((this._cTipoPago != value))
				{
					this.OncTipoPagoChanging(value);
					this.SendPropertyChanging();
					this._cTipoPago = value;
					this.SendPropertyChanged("cTipoPago");
					this.OncTipoPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cNroTransaccion", DbType="VarChar(15)")]
		public string cNroTransaccion
		{
			get
			{
				return this._cNroTransaccion;
			}
			set
			{
				if ((this._cNroTransaccion != value))
				{
					this.OncNroTransaccionChanging(value);
					this.SendPropertyChanging();
					this._cNroTransaccion = value;
					this.SendPropertyChanged("cNroTransaccion");
					this.OncNroTransaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDireccionDestinatario", DbType="varchar(100) NULL", CanBeNull=false)]
		public string cDireccionDestinatario
		{
			get
			{
				return this._cDireccionDestinatario;
			}
			set
			{
				if ((this._cDireccionDestinatario != value))
				{
					this.OncDireccionDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._cDireccionDestinatario = value;
					this.SendPropertyChanged("cDireccionDestinatario");
					this.OncDireccionDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDepartamento", DbType="varchar(2) NULL", CanBeNull=false)]
		public string codDepartamento
		{
			get
			{
				return this._codDepartamento;
			}
			set
			{
				if ((this._codDepartamento != value))
				{
					this.OncodDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._codDepartamento = value;
					this.SendPropertyChanged("codDepartamento");
					this.OncodDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProvincia", DbType="varchar(2) NULL", CanBeNull=false)]
		public string codProvincia
		{
			get
			{
				return this._codProvincia;
			}
			set
			{
				if ((this._codProvincia != value))
				{
					this.OncodProvinciaChanging(value);
					this.SendPropertyChanging();
					this._codProvincia = value;
					this.SendPropertyChanged("codProvincia");
					this.OncodProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDistrito", DbType="varchar(2) NULL", CanBeNull=false)]
		public string codDistrito
		{
			get
			{
				return this._codDistrito;
			}
			set
			{
				if ((this._codDistrito != value))
				{
					this.OncodDistritoChanging(value);
					this.SendPropertyChanging();
					this._codDistrito = value;
					this.SendPropertyChanged("codDistrito");
					this.OncodDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Pedido_TB_DetallePedido", Storage="_TB_DetallePedido", ThisKey="Pk_ePedido", OtherKey="Fk_ePedido")]
		public EntitySet<TB_DetallePedido> TB_DetallePedido
		{
			get
			{
				return this._TB_DetallePedido;
			}
			set
			{
				this._TB_DetallePedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Cliente_TB_Pedido", Storage="_TB_Cliente", ThisKey="Fk_eCliente", OtherKey="Pk_eCliente", IsForeignKey=true)]
		public TB_Cliente TB_Cliente
		{
			get
			{
				return this._TB_Cliente.Entity;
			}
			set
			{
				TB_Cliente previousValue = this._TB_Cliente.Entity;
				if (((previousValue != value) 
							|| (this._TB_Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Cliente.Entity = null;
						previousValue.TB_Pedido.Remove(this);
					}
					this._TB_Cliente.Entity = value;
					if ((value != null))
					{
						value.TB_Pedido.Add(this);
						this._Fk_eCliente = value.Pk_eCliente;
					}
					else
					{
						this._Fk_eCliente = default(int);
					}
					this.SendPropertyChanged("TB_Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_DetallePedido(TB_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.TB_Pedido = this;
		}
		
		private void detach_TB_DetallePedido(TB_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.TB_Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DetallePedido")]
	public partial class TB_DetallePedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_eDetalePedido;
		
		private int _Fk_ePedido;
		
		private int _Fk_eProducto;
		
		private int _eCantidad;
		
		private decimal _mSuTotal;
		
		private EntityRef<TB_Pedido> _TB_Pedido;
		
		private EntityRef<TB_Producto> _TB_Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_eDetalePedidoChanging(int value);
    partial void OnPk_eDetalePedidoChanged();
    partial void OnFk_ePedidoChanging(int value);
    partial void OnFk_ePedidoChanged();
    partial void OnFk_eProductoChanging(int value);
    partial void OnFk_eProductoChanged();
    partial void OneCantidadChanging(int value);
    partial void OneCantidadChanged();
    partial void OnmSuTotalChanging(decimal value);
    partial void OnmSuTotalChanged();
    #endregion
		
		public TB_DetallePedido()
		{
			this._TB_Pedido = default(EntityRef<TB_Pedido>);
			this._TB_Producto = default(EntityRef<TB_Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_eDetalePedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pk_eDetalePedido
		{
			get
			{
				return this._Pk_eDetalePedido;
			}
			set
			{
				if ((this._Pk_eDetalePedido != value))
				{
					this.OnPk_eDetalePedidoChanging(value);
					this.SendPropertyChanging();
					this._Pk_eDetalePedido = value;
					this.SendPropertyChanged("Pk_eDetalePedido");
					this.OnPk_eDetalePedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_ePedido", DbType="Int NOT NULL")]
		public int Fk_ePedido
		{
			get
			{
				return this._Fk_ePedido;
			}
			set
			{
				if ((this._Fk_ePedido != value))
				{
					if (this._TB_Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_ePedidoChanging(value);
					this.SendPropertyChanging();
					this._Fk_ePedido = value;
					this.SendPropertyChanged("Fk_ePedido");
					this.OnFk_ePedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_eProducto", DbType="Int NOT NULL")]
		public int Fk_eProducto
		{
			get
			{
				return this._Fk_eProducto;
			}
			set
			{
				if ((this._Fk_eProducto != value))
				{
					if (this._TB_Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_eProductoChanging(value);
					this.SendPropertyChanging();
					this._Fk_eProducto = value;
					this.SendPropertyChanged("Fk_eProducto");
					this.OnFk_eProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eCantidad", DbType="Int NOT NULL")]
		public int eCantidad
		{
			get
			{
				return this._eCantidad;
			}
			set
			{
				if ((this._eCantidad != value))
				{
					this.OneCantidadChanging(value);
					this.SendPropertyChanging();
					this._eCantidad = value;
					this.SendPropertyChanged("eCantidad");
					this.OneCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mSuTotal", DbType="Money NOT NULL")]
		public decimal mSuTotal
		{
			get
			{
				return this._mSuTotal;
			}
			set
			{
				if ((this._mSuTotal != value))
				{
					this.OnmSuTotalChanging(value);
					this.SendPropertyChanging();
					this._mSuTotal = value;
					this.SendPropertyChanged("mSuTotal");
					this.OnmSuTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Pedido_TB_DetallePedido", Storage="_TB_Pedido", ThisKey="Fk_ePedido", OtherKey="Pk_ePedido", IsForeignKey=true)]
		public TB_Pedido TB_Pedido
		{
			get
			{
				return this._TB_Pedido.Entity;
			}
			set
			{
				TB_Pedido previousValue = this._TB_Pedido.Entity;
				if (((previousValue != value) 
							|| (this._TB_Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Pedido.Entity = null;
						previousValue.TB_DetallePedido.Remove(this);
					}
					this._TB_Pedido.Entity = value;
					if ((value != null))
					{
						value.TB_DetallePedido.Add(this);
						this._Fk_ePedido = value.Pk_ePedido;
					}
					else
					{
						this._Fk_ePedido = default(int);
					}
					this.SendPropertyChanged("TB_Pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Producto_TB_DetallePedido", Storage="_TB_Producto", ThisKey="Fk_eProducto", OtherKey="Pk_eProducto", IsForeignKey=true)]
		public TB_Producto TB_Producto
		{
			get
			{
				return this._TB_Producto.Entity;
			}
			set
			{
				TB_Producto previousValue = this._TB_Producto.Entity;
				if (((previousValue != value) 
							|| (this._TB_Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Producto.Entity = null;
						previousValue.TB_DetallePedido.Remove(this);
					}
					this._TB_Producto.Entity = value;
					if ((value != null))
					{
						value.TB_DetallePedido.Add(this);
						this._Fk_eProducto = value.Pk_eProducto;
					}
					else
					{
						this._Fk_eProducto = default(int);
					}
					this.SendPropertyChanged("TB_Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ubigeo")]
	public partial class Ubigeo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codDepartamento;
		
		private string _codProvincia;
		
		private string _codDistrito;
		
		private string _departamento;
		
		private string _provincia;
		
		private string _distrito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodDepartamentoChanging(string value);
    partial void OncodDepartamentoChanged();
    partial void OncodProvinciaChanging(string value);
    partial void OncodProvinciaChanged();
    partial void OncodDistritoChanging(string value);
    partial void OncodDistritoChanged();
    partial void OndepartamentoChanging(string value);
    partial void OndepartamentoChanged();
    partial void OnprovinciaChanging(string value);
    partial void OnprovinciaChanged();
    partial void OndistritoChanging(string value);
    partial void OndistritoChanged();
    #endregion
		
		public Ubigeo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDepartamento", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codDepartamento
		{
			get
			{
				return this._codDepartamento;
			}
			set
			{
				if ((this._codDepartamento != value))
				{
					this.OncodDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._codDepartamento = value;
					this.SendPropertyChanged("codDepartamento");
					this.OncodDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProvincia", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codProvincia
		{
			get
			{
				return this._codProvincia;
			}
			set
			{
				if ((this._codProvincia != value))
				{
					this.OncodProvinciaChanging(value);
					this.SendPropertyChanging();
					this._codProvincia = value;
					this.SendPropertyChanged("codProvincia");
					this.OncodProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDistrito", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codDistrito
		{
			get
			{
				return this._codDistrito;
			}
			set
			{
				if ((this._codDistrito != value))
				{
					this.OncodDistritoChanging(value);
					this.SendPropertyChanging();
					this._codDistrito = value;
					this.SendPropertyChanged("codDistrito");
					this.OncodDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string departamento
		{
			get
			{
				return this._departamento;
			}
			set
			{
				if ((this._departamento != value))
				{
					this.OndepartamentoChanging(value);
					this.SendPropertyChanging();
					this._departamento = value;
					this.SendPropertyChanged("departamento");
					this.OndepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this.OnprovinciaChanging(value);
					this.SendPropertyChanging();
					this._provincia = value;
					this.SendPropertyChanged("provincia");
					this.OnprovinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this.OndistritoChanging(value);
					this.SendPropertyChanging();
					this._distrito = value;
					this.SendPropertyChanged("distrito");
					this.OndistritoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
